//
// Category.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Categories: Codable {

    public var _id: Int?
    public var categoryName: String?


    public init(_id: Int?, categoryName: String?) {
        self._id = _id
        self.categoryName = categoryName

    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case categoryName = "category_name"

    }


}

